// Benchmark Engine - Compares prompt-generated trades vs classic technical strategies
// Runs the same backtest conditions for all participants

import { runBacktest } from './backtestEngine'
import { STRATEGIES, runStrategy } from './technicalStrategies'

/**
 * Run a benchmark comparison
 * @param {Object} params
 * @param {Array} params.promptTrades - Trades generated by the AI prompt
 * @param {string[]} params.strategyIds - Classic strategy IDs to compare against
 * @param {Object} params.historicalData - { 'BTC/USDT': candles[], ... }
 * @param {string[]} params.assets - Assets to run strategies on
 * @param {number} params.initialCapital
 * @param {number} params.leverage
 * @param {number} params.slippage
 * @param {number} params.takerFee
 * @param {function} params.onProgress - (step, total, label)
 * @returns {Object} Benchmark results with rankings
 */
export const runBenchmark = async (params) => {
  const {
    promptTrades = [],
    promptName = 'AI Prompt',
    strategyIds = [],
    historicalData = {},
    assets = [],
    initialCapital = 1000,
    leverage = 1,
    slippage = 0.001,
    takerFee = 0.001,
    onProgress
  } = params

  const totalSteps = strategyIds.length + 1 // +1 for prompt backtest
  let currentStep = 0

  const backtestConfig = { historicalData, initialCapital, leverage, slippage, takerFee }

  // 1. Backtest the prompt trades
  onProgress?.(currentStep, totalSteps, `Backtesting ${promptName}...`)
  const promptResult = runBacktest({ ...backtestConfig, trades: promptTrades })
  currentStep++

  const results = [{
    id: 'prompt',
    name: promptName,
    shortName: promptName.length > 16 ? promptName.slice(0, 14) + '...' : promptName,
    type: 'prompt',
    icon: '🧠',
    totalTrades: promptResult.totalTrades,
    ...promptResult
  }]

  // 2. Generate signals from each classic strategy and backtest them
  for (const strategyId of strategyIds) {
    const strategy = STRATEGIES[strategyId]
    if (!strategy) continue

    onProgress?.(currentStep, totalSteps, `Running ${strategy.name}...`)

    // Generate signals across all assets
    const allSignals = []
    for (const asset of assets) {
      const candles = historicalData[asset]
      if (!candles || candles.length === 0) continue

      try {
        const signals = runStrategy(strategyId, candles, asset)
        allSignals.push(...signals)
      } catch (err) {
        console.warn(`Strategy ${strategyId} failed for ${asset}:`, err)
      }
    }

    // Backtest the strategy signals
    const stratResult = runBacktest({ ...backtestConfig, trades: allSignals })

    results.push({
      id: strategyId,
      name: strategy.name,
      shortName: strategy.shortName,
      type: 'classic',
      icon: strategy.icon,
      params: strategy.params,
      totalTrades: stratResult.totalTrades,
      ...stratResult
    })

    currentStep++
  }

  // 3. Rank by total PnL
  results.sort((a, b) => b.totalPnlPercent - a.totalPnlPercent)
  results.forEach((r, i) => { r.rank = i + 1 })

  // 4. Calculate relative metrics
  const bestPnl = results[0]?.totalPnlPercent || 0
  const worstPnl = results[results.length - 1]?.totalPnlPercent || 0

  results.forEach(r => {
    r.relativeStrength = bestPnl !== worstPnl
      ? ((r.totalPnlPercent - worstPnl) / (bestPnl - worstPnl)) * 100
      : 50
  })

  return {
    results,
    promptName,
    assets,
    totalStrategies: results.length,
    promptRank: results.find(r => r.type === 'prompt')?.rank || 0,
    bestStrategy: results[0]?.name || 'None',
    createdAt: new Date().toISOString()
  }
}

/**
 * Generate a comparison matrix for radar chart
 */
export const generateRadarData = (results) => {
  if (!results || results.length === 0) return []

  // Metrics to compare (normalized 0-100)
  const metrics = ['winRate', 'profitFactor', 'sharpeRatio', 'totalPnlPercent', 'totalTrades']
  const labels = ['Win Rate', 'Profit Factor', 'Sharpe', 'PnL %', 'Trades']

  // Find max values for normalization
  const maxValues = {}
  metrics.forEach(m => {
    maxValues[m] = Math.max(...results.map(r => Math.abs(r[m] || 0)), 1)
  })

  return results.map(r => ({
    name: r.shortName || r.name,
    type: r.type,
    values: metrics.map((m, i) => ({
      label: labels[i],
      value: Math.max(0, ((r[m] || 0) / maxValues[m]) * 100),
      raw: r[m] || 0
    }))
  }))
}
